baseURL = "https://www.jamesh.id.au/"
languageCode = "en-au"
title = "James Henstridge"
theme = "ananke"
enableGitInfo = true
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "monokai"

[pagination]
pagerSize = 25

[permalinks]
blog = "/blog/:year/:month/:day/:slugorcontentbasename/"

[params]
mainSections = ["post"]

[params.ananke.social.follow]
networks = ["mastodon", "linkedin", "github"]

[params.ananke.social.share]
networks = []

[params.ananke.social.mastodon]
username = "@jamesh@aus.social"
profilelink = "https://aus.social/@jamesh"
rel = "me"
[params.ananke.social.twitter]
username = "jameshenstridge"
[params.ananke.social.facebook]
username = "james.henstridge"
[params.ananke.social.linkedin]
username = "jameshenstridge"
profilelink = "https://www.linkedin.com/in/jameshenstridge/"
[params.ananke.social.github]
username = "jhenstridge"

[related]
threshold = 80
includeNewer = true
toLower = false
[[related.indices]]
name = "tags"
weight = 50
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"
